# loads all the libraries needed for the app. 
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(tidyverse)
library(here)
library(magrittr)
library(plotly)
library(r2d3)
library(glue)
library(network3d)
library(DT)
library(shinyjs)
# devtools::install_github('tbilab/meToolkit')
# devtools::install_github("DivadNojnarg/shinydashboardPlus")
# devtools::install_github("JhuangLab/annovarR")
# annovarR::web()
